import dash
from dash import html, dcc
import dash_bootstrap_components as dbc

titulo_0 = html.H5('Sobre este trabalho')
par_0_0 = html.P('''Este trabalho tem o intuito de apresentar os números relacionados à campanha às eleições municipais de Belo Horizonte pela UP em termos da apresentação dos números do partido e comparação destes números com os números de outros partidos para uma avaliação educada do desempenho partidário.''')
par_0_1 = html.P('''O trabalho é dividido em três páginas. Esta página (Página inicial) apresenta um rápido resumo dos principais indicadores do desempenho do partido assim como uma rápida análise preliminar dos números, que devem ainda ser entendidos e debatidos em outra oportunidade. A página "Análise do desempenho eleitoral do partido" apresenta os números relacionados ao partido e seus candidatos assim como comparações específicas com os números de outros partidos ou propriedades do certame como custos médios dos vereadores eleitos em partidos selecionados. A página "Resumo do desempenho dos partidos" se refere a uma abordagem geral do desempenho dos partidos que pode também ser filtrada de diversas formas e visualizadas nos mapas apresentados.''')
titulo_1 = html.H5('Resumo')
par_1 = html.P('''Este trabalho tem o intuito de analisar e explicar os resultados observados no primeiro turno das eleições municipais de Belo Horizonte usando os dados disponíveis pelo TSE. Como resultados positivos os números mostram que os candidatos da UP à vereança estiveram entre os 7 candidatos com votos mais baratos do pleito (considerando-se a soma dos candidatos, a UP teve o voto mais barato de todos) com destaque à candidata Mari Fernandes que teve o segundo voto mais barato (perdendo o primeiro lugar para o candidato Pablo Almeida, candidato da igreja batista da Lagoinha). Outros resultados bastante positivos é a ocupação das urnas, que mede o percentual de urnas que recebeu ao menos um voto na UP, que tem média de 61% com destaques a zona 26 com 80% de ocupação das urnas e a zona 33 com 76%. Citamos também como boas notícias o auto percentual de votos ideológicos ao partido (votos na legenda à vereança, que corresponde a mais de 16% dos votos contabilizados); o voto mais barato a prefeitura, da candidata Indira Xavier, e que a soma de votos a vereança do partido foi em torno de 3700 voto, mas o candidato com menor votação entre os eleitos, o candidato Neném da Farmácia, contabilizou pouco mais de 4700 votos.''')
par_1_2 = html.P('''Outro fato positivo embora de menor importância é o fato que todos os candidatos, sejam eles lideranças locais ou lideranças regionais receberam votos de todas as regiões da cidade. Algumas urnas até mesmo registraram votos para todos os candidatos ao pleito.''')
par_2 = html.P(''' Quanto aos problemas mais evidentes, podemos começar pelo número de votos no partido que ainda é muito pequeno, embora o partido tenha recebido mais votos que os outros partidos da esquerda radical somados, e, que esta seja a primeira eleição municipal do partido. Outro problema é justamente a ocupação das urnas. Embora os números sejam impressionantes para um partido da esquerda radical com três anos de idade e sem recursos, o fato de não estarmos em todas as urnas, em especial das zonas eleitorais representando a parcela mais pobre da população, como as zonas 38, 39, 36 e 333, indica que muito trabalho de divulgação do partido precisa ser feito.''')
titulo_2 = html.H5('O que não fazer segundo os dados')
par_3 = html.P(''' Intensionalmente aglutinamos os votos aos partidos de esquerda tanto a vereança quanto à prefeitura porque uma sugestão insistente sobre toda falha da esquerda, seja essa falha real ou não, em que consiste em clamar por uma união abstrata quaisquer que sejam os termos. Os dados mostram que essa sugestão, ao menos nas últimas eleições é no mínimo inefetiva. Assumindo que a forma concreta esta sugestão quanto ao pleito para a prefeitura seja a designação de apenas um candidato (quem quer que seja) que em tese absorveria os votos de todos os outros candidatos numa candidatura única similar ao que foi feito nas últimas eleições francesas, então os dados mostram que estes votos somariam apenas 10% dos votos. Somando-se os votos dos indecisos (brancos e nulos), a esta "frente ampla" sob o argumento que tal manobra seja único na história politica recente que atraia os votos dos indecisos, chegamos a 22% dos votos. Ou seja, tal manobra não teria votos para ir sequer ao segundo turno (o segundo lugar recebeu 24% dos votos no primeiro turno). O senário não muda quanto ao pleito à vereança em que apesar de mais partidos fazerem parte da hipotética frente política, a soma dos votos a esquerda somaram pouco mais de 15%, ou pouco mais de 29% somando-se os votos nulos e brancos.''')

par_4 = html.P('''Outra sugestão igualmente abstrata é "falta organização da esquerda" e é usada muitas vezes por pessoas longe, por um motivo ou outro, das dinâmicas internas do partido. Continuando, considerando-se que o sentido da acusação de desorganização seja relacionado com os gastos do partido apontamos que apesar das eventuais falhas e gastos que poderiam ser evitados, ou melhor aplicados em outras ações, tivemos o voto mais barato a prefeito, entre os votos mais baratos a vereança e, somando votos a vereança e a prefeito, os votos mais baratos sobre todos os demais partidos. Não obstante, observamos que o candidato mais "barato" eleito pela esquerda foi o candidato Edmar Branco, pelo PCdoB que declarou o gasto de quase 140 mil reais na campanha. Compare com a campanha da candidata Mari Fernandes (a candidata a vereança com maior investimento do partido), que declarou pouco mais de 21 mil reais. Além disso, o gasto médio para vereadores eleitos é astronômico mesmo entre partidos conhecidos. O custo médio do vereador eleito pelo PT foi de 447 mil reais ao passo que o custo do candidato eleito pelo PL chegou a 396 mil reais. Caso o que se deseja informar apontando uma suposta desorganização se refira a organização do trabalho de divulgação das candidaturas, então se trata de um ponto interessante que requer maior cuidado e será apresentado a seguir.''')
par_5 = html.P('''Continuando a discussão sobre organização, pode-se argumentar que "organização" seja sinônimo de quantidade de militantes atuando nas campanhas nas ruas. Observando-se que o dinheiro gasto declarado pelos partidos de forma geral é utilizado para a produção de material de propaganda e também para a produção de trabalho como a distribuição deste material, e observando-se também que os trabalhos dos militantes da UP durante a campanha é voluntário, esta crítica recai novamente à falta de recursos financeiros, uma vez que uma das principais justificativas dos militantes ao não participarem das atividades é falta de tempo relacionada ao trabalho, o que poderia ser mitigado com pagamento pelos serviços prestados (embora tal "solução" traria outra sorte de problemas).''')

titulo_3 = html.H5('O que fazer segundo os dados')
par_6 = html.P('''A UP como um partido Leninista-Marxista com ênfase nas lutas práticas e consciência politica de seus militantes, teria significativa vantagem caso as condições de pleito fossem de fato democráticas. Dito isto, é razoável se supor que esta situação não mudará para os próximos pleitos de forma que é preciso buscar soluções internas aos problemas identificados. A seguir apresentam-se algumas sugestões:''')
item_1 = html.Ul('''**O problema da disponibilidade de recursos**: é fundamental que cada filiade contribua com o partido da forma que puder para garantir o funcionamento das atividades do partido; garantir o aprimoramento das atividades em curso; acolhimento e organização de novas lutas. Mais concretamente, o partido precisa de uma equipe de divulgação e propaganda que atue em tempo integral, precisamos de uma equipe de transporte para tornar as lutas pela cidade mais acessíveis aos militantes, em especial aos que vão aos locais a primeira vez, e precisamos também de apoio financeiro direto para os atos relacionados aos movimentos e locais físicos permanentes onde podemos montar atividades específicas. Este é o principal problema porque a contribuição mensal dos filiades girava em uma média de 30%, mas durante as eleições, o período mais importante para se contribuir para com o partido, essa cifra chegou a cair a 10% o que sabotou os esforços dos militantes engajados na luta e nossos candidatos.''')
item_2 = html.Ul('''**O problema da participação dos militantes na campanha**: é preciso aumentar o percentual de participação dos militantes como uma forma de otimizar os poucos recursos do partido. Embora a justificativa de falta de tempo em função do trabalho e/ou família seja seríssima, haja vista que somos todos trabalhadores e sofremos o mesmo qualquer que seja a ocupação, ainda é verdade que a campanha pelo partido e pelas lutas pode ser feita entre vizinhos, entre amigos, na família, na escola, durante os trajetos, etc. é perfeitamente razoável que o militante guarde parte dos panfletos, jornais, informes, conteúdos do partido nas redes e conversar sobre eles sempre que possível, assim como foi feito por alguns militantes durante a campanha de 2024.''')
item_3 = html.Ul('''**O problema do convencimento**: os dados mostram que mesmo em áreas de atuação dos candidatos recebemos um percentual baixo de votos em relação ao total de pessoas organizadas nos movimentos (não necessariamente no partido). Olhando para o perfil de candidatos com alto percentual de votos observamos que ou são apresentados como: candidatos de outras figuras políticas poderosas; candidatos a reeleição relacionados à injeção de recursos públicos em diversos projetos; candidatos envolvidos em projetos de capital privado; são candidatos oriundos de profissões bem-vistas como policiais e empresários. Portanto, é razoável se supor que o convencimento mais efetivo da população se dá por meio de ações concretas em projetos que a comunidade local valora, o que já é feito pelo partido em alguns pontos da cidade, por apoios de figuras poderosas, ou por mostra de uma perspectiva de futuro. Seja atuação em ONGs, seja em atuação em projetos, ou seja no caso de pertencimento às profissões específicas as pessoas esperam a manutenção de tais projetos, participação no campo de atividade do candidato ou mesmo maior liberdade de atuação de tais profissões, as pessoas tendem a acreditar num valor futuro ou numa melhora em relação a problemas específicos. Portanto, um caminho possível para se atrair mais militantes e eleitores é a apresentação de possíveis projetos de resolução de problemas comuns. Por exemplo, embora seja comum entre entregadores o sonho do empresariado é notória a exploração dos detentores do aplicativo sobre seu trabalho, logo uma proposta fácil de se entender e lutar é pela produção de um aplicativo da prefeitura com capacidade de competir com os aplicativos tradicionais, mas com mais proteção e menos exploração para os motoristas. É claro, pode-se compor um panfleto distribuído com certa antecedência, mas para colocar essa ideia em campos mais firmes com estimativas de custo realistas é preciso que a militância se dedique também a essa tarefa. Enfatizamos que estas ultimas linhas se tratam apenas da exploração de exemplo e que produção de aplicativos não é o objetivo final do partido e qualquer projeto do tipo deve sempre ser agraciado com bastante deliberação, debate e estudo. Mas o ponto é que projetos ou sugestões de um futuro tangível que pode ser obtido através da luta e da confiança no partido é um possível caminho para angariar votos e inflamar militantes que pode ser executado em conjunto com a ampliação dos projetos práticos do partido como a luta por moradia e luta estudantil.''')
texto = html.Div([
        html.P(' '),
        titulo_0,
        par_0_0,
        par_0_1,
        titulo_1,
        par_1,
        par_2,
        titulo_2,
        par_3,
        par_4,
        par_5,
        titulo_3,
        par_6,
        item_1,
        item_2,
        item_3
        ])


#html.P('Dash converts Python classes into HTML')
layout = html.Div([
            dbc.Row([html.H4('Página inicial'),
                    dash.register_page(__name__, path='/'),
                    html.H5('Uma breve discussão sobre os números'),
                    texto
                    ])
        ])